# frontend/Dockerfile.dev
FROM node:22-bullseye-slim AS build
WORKDIR /app

COPY package*.json ./
RUN apt-get update && apt-get install -y python3 make g++ bash && rm -rf /var/lib/apt/lists/*
RUN npm install

COPY . .
RUN npm run build

# Étape nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
