version: "3.9"

services:
  backend:
    build: ./backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    env_file:
      - .env
    environment:
      - DEBUG=0
    depends_on:
      - db
    networks:
      - buxium-network
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - buxium-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    networks:
      - buxium-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - backend_static:/static
      - backend_media:/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - buxium-network
    restart: unless-stopped

volumes:
  postgres_data:
  backend_static:
  backend_media:

networks:
  buxium-network:
    driver: bridge