services:
  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
    depends_on:
      - db
    networks:
      - buxium-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: buxium_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abdoul1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - buxium-network

  redis:  # ← AJOUTER CE SERVICE
    image: redis:7-alpine
    networks:
      - buxium-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    command: sh -c "npm ci --silent && npm run dev"
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - buxium-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - backend_static:/static
      - backend_media:/media
    depends_on:
      - backend
      - frontend
    networks:
      - buxium-network

volumes:
  postgres_data:
  backend_static:
  backend_media:

networks:
  buxium-network:
    driver: bridge