# Generated by Django 5.0.7 on 2025-09-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.entreprise')),
            ],
            options={
                'unique_together': {('entreprise', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Marchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seq', models.PositiveIntegerField(editable=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marchandises/')),
                ('designation', models.CharField(max_length=100)),
                ('unite', models.CharField(max_length=20)),
                ('seuil', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marchandises', to='gestion_stock.categorie')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marchandises', to='accounts.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seq', models.PositiveIntegerField(editable=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='accounts.entreprise')),
                ('marchandises', models.ManyToManyField(blank=True, related_name='fournisseurs', to='gestion_stock.marchandise')),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees', to='gestion_stock.marchandise')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties', to='gestion_stock.marchandise')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Dépense')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.entreprise')),
            ],
        ),
        migrations.AddIndex(
            model_name='marchandise',
            index=models.Index(fields=['entreprise', 'num_seq'], name='gestion_sto_entrepr_6c33ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marchandise',
            unique_together={('entreprise', 'reference')},
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['entreprise', 'num_seq'], name='gestion_sto_entrepr_ce3bad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fournisseur',
            unique_together={('entreprise', 'reference')},
        ),
    ]
